### ISSUE TITLE
Can't update existing store to add expiry

### ISSUE THREAD

**Issue by visualspark** [sirLisko/redux-persist-transform-expire-in#16]
The plugin doesn't take into account adding as a new feature to an existing store and only works with brand new persisted stores.

**Comment by sirlisko** [comment]
Do you have an example I can look at?
Are you by any chance using another persistent store?

**Comment by visualspark** [comment]
Not code that I can share as its part of a live app, and yes I am using react-persist with redux-persist-transform-encrypt. The following steps outline my use case:

1. Create an app with react-persist and not your transform
2. Persist data from the app and then retrieve it
3. add your transform setting your expiry etc
4. data is not retrieved, only your default state of an empty object.

The issue is in your resolution of expired. By default everything is expired until proven not. You need to return the original state if you can't find the expired key, rather than your default as an empty object.  

https://github.com/sirLisko/redux-persist-transform-expire-in/blob/fe632fd56795875e3b462c0b1619d5edf1bbbcd2/src/index.ts#L20

**Comment by sirlisko** [comment]
It makes sense, it has been fixed in https://github.com/sirLisko/redux-persist-transform-expire-in/pull/17 and published to npm as `1.1.2`.
